run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errorlint
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - ifshort
    - ireturn
    - lll
    - misspell
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - thelper
    - gofumpt
