language: go

go:
  - 1.13.x

services:
  - docker

before_install:
  # Get latest docker version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  # Get Nigiri-travis for testing
  - mkdir -p tmp; cd tmp
  - curl https://travis.nigiri.network | bash; cd ..
  - docker-compose -f tmp/docker-compose.yml up -d

env:
  - API_URL=http://localhost:3001

script:
  - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted"; exit 1; fi
  - go test -count=1 ./... -v

after_script:
  - docker-compose -f tmp/docker-compose.yml down && rm -rf tmp
