language: go

go:
  - 1.14.x

services:
  - docker

install:
  # Get Nigiri-travis for testing
  - mkdir -p tmp; cd tmp
  - curl https://travis.nigiri.network | bash; cd ..
  - docker-compose -f tmp/docker-compose.yml up -d

env:
  - API_URL=http://localhost:3001

script:
  - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted"; exit 1; fi
  - go test -count=1 -race ./... -v

after_script:
  - docker-compose -f tmp/docker-compose.yml down && rm -rf tmp
